In [23]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [24]:
data = [
    ['Red', 'Small', 'Apple'],
    ['Green', 'Large', 'Banana'],
    ['Yellow', 'Medium', 'Banana'],
    ['Red', 'Medium', 'Apple'],
    ['Green', 'Small', 'Apple'],
     ['Green', 'Large', 'Banana'],
    ['Yellow', 'Large', 'Orange'],
    ['Green', 'Medium', 'Banana'],
     ['Green', 'Large', 'Banana'],
    ['Yellow', 'Small', 'Apple'],
    ['Red', 'Large', 'Orange']
]

In [25]:
data=np.array(data)

In [26]:
print(data)

[['Red' 'Small' 'Apple']
 ['Green' 'Large' 'Banana']
 ['Yellow' 'Medium' 'Banana']
 ['Red' 'Medium' 'Apple']
 ['Green' 'Small' 'Apple']
 ['Green' 'Large' 'Banana']
 ['Yellow' 'Large' 'Orange']
 ['Green' 'Medium' 'Banana']
 ['Green' 'Large' 'Banana']
 ['Yellow' 'Small' 'Apple']
 ['Red' 'Large' 'Orange']]


In [27]:
data=np.array(data)

In [28]:
data

array([['Red', 'Small', 'Apple'],
       ['Green', 'Large', 'Banana'],
       ['Yellow', 'Medium', 'Banana'],
       ['Red', 'Medium', 'Apple'],
       ['Green', 'Small', 'Apple'],
       ['Green', 'Large', 'Banana'],
       ['Yellow', 'Large', 'Orange'],
       ['Green', 'Medium', 'Banana'],
       ['Green', 'Large', 'Banana'],
       ['Yellow', 'Small', 'Apple'],
       ['Red', 'Large', 'Orange']], dtype='<U6')

In [29]:
type(data)

numpy.ndarray

In [30]:
color_map = {'Red': 0, 'Green': 1, 'Yellow': 2}
size_map = {'Small': 0, 'Medium': 1, 'Large': 2}
fruit_map = {'Apple': 0, 'Banana': 1, 'Orange': 2}

In [31]:
X = np.array([[color_map[color], size_map[size]] for color, size in data[:, :2]])  # Features (Color, Size)
y = np.array([fruit_map[fruit] for fruit in data[:, 2]])  # Target (Fruit Type)

In [32]:
print(X)
print(y)

[[0 0]
 [1 2]
 [2 1]
 [0 1]
 [1 0]
 [1 2]
 [2 2]
 [1 1]
 [1 2]
 [2 0]
 [0 2]]
[0 1 1 0 0 1 2 1 1 0 2]


In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [34]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [35]:
y_pred = knn.predict(X_test)

In [36]:
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred, target_names=list(fruit_map.keys()), zero_division=1)
conf_matrix = confusion_matrix(y_test, y_pred)

# Output the results
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_rep)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.5
Classification Report:
               precision    recall  f1-score   support

       Apple       1.00      0.50      0.67         2
      Banana       0.33      1.00      0.50         1
      Orange       1.00      0.00      0.00         1

    accuracy                           0.50         4
   macro avg       0.78      0.50      0.39         4
weighted avg       0.83      0.50      0.46         4

Confusion Matrix:
 [[1 1 0]
 [0 1 0]
 [0 1 0]]


In [39]:
def predict_new_fruit(color, size):
    color_encoded = color_map[color]
    size_encoded = size_map[size]

    new_data = np.array([[color_encoded, size_encoded]])
    prediction = knn.predict(new_data)[0]

    fruit_name = [k for k, v in fruit_map.items() if v == prediction][0]

    return fruit_name

In [40]:
new_color = 'Green'
new_size = 'Medium'
predicted_label = predict_new_fruit(new_color, new_size)
print(f"The predicted fruit for color '{new_color}' and size '{new_size}' is: {predicted_label}")

The predicted fruit for color 'Green' and size 'Medium' is: Banana
